### PR TITLE
enable failOnValidation and fix issues related to the new checkstyle version

### LINKED ISSUE #1111: checkstyle checks are not working on the codebase

### PR DESCRIPTION
**Pull request by dmitry-s**
fixes #1111

### CODE REVIEW

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubEmulator.java [hunk 1]
```diff
@@ -137,6 +126,21 @@ protected void after() {
 		}
 	}
 
+	private int validateEmulator() {
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubEmulator.java]: findAndDestroyEmulator? Or something less clunky but still descriptive...
I like the refactoring into a separate method, but it does more than validate.

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateTests.java [hunk 2]
```diff
@@ -167,12 +175,9 @@ public void setup() {
 
 		// Because get() takes varags, there is difficulty in matching the single param
 		// case using just thenReturn.
-		doAnswer(invocation -> {
-			Object key = invocation.getArgument(0);
-			return key instanceof Key && key == this.key1
-					? ImmutableList.of(this.e1).iterator()
-					: null;
-		}).when(this.datastore).get((Key[]) any());
+		doAnswer(invocation -> invocation.getArgument(0) instanceof Key && invocation.getArgument(0) == this.key1
```
[the remark this answers is not in the document]
Comment (dmitry-s) [reply spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateTests.java]: @elefeint 
It was because of number of returns per method restriction

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/PartTreeSpannerQuery.java [hunk 3]
```diff
@@ -57,26 +58,30 @@ protected List executeRawResult(Object[] parameters) {
...
-						}
-						return result;
-					});
+					.performReadWriteTransaction(getDeleteFunction(parameters));
 		}
 		return SpannerStatementQueryExecutor.executeQuery(this.entityType, this.tree,
 						parameters, this.spannerTemplate, this.spannerMappingContext);
 	}
 
+	private Function<SpannerTemplate, List> getDeleteFunction(Object[] parameters) {
```
Comment (ChengyuanZhao) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/PartTreeSpannerQuery.java]: Honestly I think having a separate private method that returns a `Function` I think is messier than just having the contents of this method as the anonymous function directly.

Comment (dmitry-s) [reply spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/PartTreeSpannerQuery.java]: @ChengyuanZhao 
Feel free to create a PR, I was just fixing checkstyle issues.

Comment (ChengyuanZhao) [reply spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/PartTreeSpannerQuery.java]: But was this specific change flagged by checkstyle?

Comment (dmitry-s) [reply spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/PartTreeSpannerQuery.java]: @ChengyuanZhao 
it was number of returns per method issue
