### PR TITLE
Spanner array param binding

### LINKED ISSUE #1701: Spring Data Spanner Repositories `In` clause queries support
Spring data spanner gives `java.lang.UnsupportedOperationException: The statement type: IN (1): [IsIn, In] is not supported.` when trying to use `IN` for selecting columns  part of a composite key in a SpannerRepository interface
`@Query("select * from <TableName> t where t.<columnName1>= @param1 AND t.columnName2 IN (@param2)")`
```Set<OnHandInventory> findBy<ColumnName1>And<ColumnName2>In(@Param("param1") String columnOneValue,@Param("param2") Set<Long> column2Values);```

Note: Exception being thrown at [SpannerStatementQueryExecutor.java](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java#L399)

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #1701 
array param binding in queries. and IN clause

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
The Spanner module builds, but the Streams module fails..... 

@dmitry-s

**Comment by ChengyuanZhao** [comment]
@dmitry-s @meltsufin PTAL

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java [hunk 1]
```diff
@@ -193,16 +216,45 @@ public static Statement buildStatementFromSqlWithArgs(String sql, List<String> t
...
+	private static void bindArrayParameter(ValueBinder<Statement.Builder> bind,
+			SpannerCustomConverter spannerCustomConverter,
+			Iterable originalParam, Parameter paramMetadata) {
+		Iterable param = originalParam;
+		Class innerType = (Class) ((ParameterizedType) paramMetadata.getParameterizedType())
+				.getActualTypeArguments()[0];
+		BiConsumer<ValueBinder<?>, Iterable> toMethod = getIterableValueBinderBiConsumer(innerType);
+
+		// attempt conversion of elements inside
+		if (toMethod == null) {
```
Comment (dmitry-s) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java]: should this logic be in `ConverterAwareMappingSpannerEntityWriter`?

File: docs/src/main/asciidoc/spanner.adoc [hunk 2]
```diff
@@ -1038,6 +1038,8 @@ The following filter options are supported:
 * Not like a string
 * Contains a string
 * Not contains a string
+* In
+* Not in
```
Comment (dmitry-s) [inline docs/src/main/asciidoc/spanner.adoc]: we should document `IN UNNEST` syntax and when to use it instead of `IN` for @Query annotated methods

Comment (ChengyuanZhao) [reply docs/src/main/asciidoc/spanner.adoc]: done.

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java (hunk 1 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java]: I tried doing this but I decided against it. I tried extracting a method but the signature needed to have several arguments and they were rather specialized. I felt that it was an uncomfortably specialized method that shouldn't be public on ConverterAwareMappingSpannerEntityWriter

Comment (ChengyuanZhao) [reply spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java]: @dmitry-s actually great idea. I refactored . PTAL!

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java [hunk 3]
```diff
@@ -193,6 +193,81 @@ public SpannerWriteConverter getSpannerWriteConverter() {
 		return this.writeConverter;
 	}
 
+	/**
```
Comment (ChengyuanZhao) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java]: @dmitry-s  Don't be alarmed by these big new sections .They're just moved up because now they're public.
