### PR TITLE
Javadoc checkstyle enable and code fix

### LINKED ISSUE #1201: Checkstyle: enable Javadoc checks
- JavadocTypeCheck
- JavadocMethodCheck
- JavadocVariableCheck
- JavadocStyleCheck

Part of #1195.

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #1201 
enables several javadoc checkstyle rules and fixes hundreds of spots

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@dmitry-s @elefeint PTAL ! i hope this is more fun to review than it was to make

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreNativeTypes.java [hunk 1]
```diff
@@ -127,15 +133,24 @@
...
+	 * @return `true` if the type is a native type, which includes `null`. `false` otherwise.
+	 */
 	public static boolean isNativeType(Class aClass) {
 		return aClass == null || DATASTORE_NATIVE_TYPES.contains(aClass);
 	}
 
-	/*
-	* Wraps datastore native type to datastore value type
+	/**
+	* Wraps Datastore native type to Datastore value type.
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreNativeTypes.java]: indent is odd here

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/config/EnableDatastoreRepositories.java [hunk 2]
```diff
@@ -46,25 +46,29 @@
 	 * Alias for the {@link #basePackages()} attribute. Allows for more concise annotation
 	 * declarations e.g.: {@code @EnableDatastoreRepositories("org.my.pkg")} instead of
 	 * {@code @EnableDatastoreRepositories(basePackages="org.my.pkg")}.
+	 * @return an empty  array
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/config/EnableDatastoreRepositories.java]: all "an empty  array" have an extra space before "array".

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 3]
```diff
@@ -74,10 +74,12 @@
 	private SpelQueryContext.EvaluatingSpelQueryContext evaluatingSpelQueryContext;
 
 	/**
-	 * Constructor
+	 * Constructor.
 	 * @param type the underlying entity type
 	 * @param queryMethod the underlying query method to support.
 	 * @param datastoreTemplate used for executing queries.
+	 * @param evaluationContextProvider the provider used to evaluate SpEL expressions in queries.
+	 * @param gql the query text.
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: swap order of gql and evaluationContextProvider to match method parameters

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateTests.java [hunk 4]
```diff
@@ -74,10 +74,14 @@
 import static org.mockito.Mockito.when;
 
 /**
+ * Tests for the Datastore Template.
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateTests.java]: newline

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreServiceObjectToKeyFactoryTests.java [hunk 5]
```diff
@@ -36,9 +36,14 @@
 import static org.mockito.Mockito.when;
 
 /**
+ * Tests for the object to key factory.
+ *
  * @author Chengyuan Zhao
  */
 public class DatastoreServiceObjectToKeyFactoryTests {
+	/**
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreServiceObjectToKeyFactoryTests.java]: newline before

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/EntityPropertyValueProviderTests.java [hunk 6]
```diff
@@ -33,6 +33,12 @@
 
 import static org.assertj.core.api.Assertions.assertThat;
 
+/**
+ * Tests for the entity value provider.
+ * @author Dmitry Solomakha
+ * @author Chengyuan Zhao
+ *
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/EntityPropertyValueProviderTests.java]: remove newline from here; add it before first @author instead.

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/repository/support/DatastoreRepositoryFactoryBeanTests.java [hunk 7]
```diff
@@ -28,6 +28,7 @@
 import static org.mockito.Mockito.mock;
 
 /**
+ * Tests for the Datastore Repository factory bean.
```
Comment (elefeint) [inline spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/repository/support/DatastoreRepositoryFactoryBeanTests.java]: newline

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java [hunk 8]
```diff
@@ -279,6 +279,8 @@ public boolean usePropertyAccess() {
 	}
 
 	/**
+	 * Returns null.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java]: {@code null}?

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java [hunk 9]
```diff
@@ -287,6 +289,8 @@ public boolean usePropertyAccess() {
 	}
 
 	/**
+	 * Returns false.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java]: {@code false}?

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java [hunk 10]
```diff
@@ -295,6 +299,8 @@ public boolean isImmutable() {
 	}
 
 	/**
+	 * Returns null.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerCompositeKeyProperty.java]: {@code null}?

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntity.java [hunk 11]
```diff
@@ -27,7 +27,7 @@
 /**
  * Cloud Spanner specific interface for a {@link MutablePersistentEntity} stored in a Cloud
  * Spanner table.
- *
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntity.java]: bring newline back

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntityImpl.java [hunk 12]
```diff
@@ -50,7 +50,7 @@
 /**
  * Represents a Cloud Spanner table and its columns' mapping to fields within an entity
  * type.
- *
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntityImpl.java]: bring newline back

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntityInformation.java [hunk 13]
```diff
@@ -21,6 +21,8 @@
 import org.springframework.data.repository.core.support.AbstractEntityInformation;
 
 /**
+ * Holds a Spanner persistent entity and its key type.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentEntityInformation.java]: newline

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/AbstractSpannerQuery.java [hunk 14]
```diff
@@ -28,6 +28,9 @@
 import org.springframework.data.repository.query.RepositoryQuery;
 
 /**
+ * Base abstract class for Spanner Query Methods.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/AbstractSpannerQuery.java]: newline

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SqlSpannerQuery.java [hunk 15]
```diff
@@ -54,6 +54,8 @@
 import org.springframework.util.StringUtils;
 
 /**
+ * A Query Method for Spanner using SQL strings.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SqlSpannerQuery.java]: newline

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/support/SimpleSpannerRepository.java [hunk 16]
```diff
@@ -33,6 +33,9 @@
 import org.springframework.util.Assert;
 
 /**
+ * The default implementation of a SpannerRepository.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/support/SimpleSpannerRepository.java]: newline

File: spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/support/SpannerRepositoryFactoryBean.java [hunk 17]
```diff
@@ -26,6 +26,10 @@
 import org.springframework.data.repository.core.support.RepositoryFactorySupport;
 
 /**
+ * Spanner Repository Factory Bean used to create factories that ultimately create repository implementations.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/support/SpannerRepositoryFactoryBean.java]: newline

File: spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/convert/SpannerWriteMethodCoverageTests.java [hunk 18]
```diff
@@ -28,6 +28,7 @@
 import static org.assertj.core.api.Assertions.assertThat;
 
 /**
+ * Tests to check for new mapping methods that appear in the Spanner client lib.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/convert/SpannerWriteMethodCoverageTests.java]: newline

File: spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerMappingContextTests.java [hunk 19]
```diff
@@ -34,6 +34,7 @@
 import static org.mockito.Mockito.verifyZeroInteractions;
 
 /**
+ * Tests for the Spanner mapping context.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerMappingContextTests.java]: newline

File: spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentPropertyImplTests.java [hunk 20]
```diff
@@ -34,11 +34,17 @@
...
+ * Tests for the Spanner persistent property.
+ *
  * @author Chengyuan Zhao
  */
 @RunWith(SpringRunner.class)
 public class SpannerPersistentPropertyImplTests {
 
+	/**
+	 * checks the exceptions' messages and types.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/core/mapping/SpannerPersistentPropertyImplTests.java]: remove newline

File: spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerQueryLookupStrategyTests.java [hunk 21]
```diff
@@ -51,6 +51,7 @@
 import static org.mockito.Mockito.when;
 
 /**
+ * Tests Spanner Query Method lookups.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerQueryLookupStrategyTests.java]: newline

File: spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryTests.java [hunk 22]
```diff
@@ -46,6 +46,7 @@
 import static org.mockito.Mockito.when;
 
 /**
+ * Tests Spanner statement queries.
```
Comment (elefeint) [inline spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryTests.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java [hunk 23]
```diff
@@ -35,6 +35,7 @@
 import org.springframework.messaging.MessageHandler;
 
 /**
+ * Message channel binder for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/config/PubSubBinderConfiguration.java [hunk 24]
```diff
@@ -32,6 +32,7 @@
 import org.springframework.context.annotation.Configuration;
 
 /**
+ * Pub/Sub binder configuration.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/config/PubSubBinderConfiguration.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubBindingProperties.java [hunk 25]
```diff
@@ -19,6 +19,7 @@
 import org.springframework.cloud.stream.binder.BinderSpecificPropertiesProvider;
 
 /**
+ * Binder-specific properties for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubBindingProperties.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubConsumerProperties.java [hunk 26]
```diff
@@ -17,9 +17,11 @@
 package org.springframework.cloud.gcp.stream.binder.pubsub.properties;
 
 /**
+ * Consumer properties for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubConsumerProperties.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubExtendedBindingProperties.java [hunk 27]
```diff
@@ -21,6 +21,7 @@
 import org.springframework.cloud.stream.binder.BinderSpecificPropertiesProvider;
 
 /**
+ * Extended binding properties for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubExtendedBindingProperties.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubProducerProperties.java [hunk 28]
```diff
@@ -17,8 +17,10 @@
 package org.springframework.cloud.gcp.stream.binder.pubsub.properties;
 
 /**
+ * Producer properties for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubProducerProperties.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java [hunk 29]
```diff
@@ -37,6 +37,7 @@
 import org.springframework.util.StringUtils;
 
 /**
+ * Provisioning provider for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubConsumerDestination.java [hunk 30]
```diff
@@ -19,6 +19,7 @@
 import org.springframework.cloud.stream.provisioning.ConsumerDestination;
 
 /**
+ * Consumer destination for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubConsumerDestination.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubProducerDestination.java [hunk 31]
```diff
@@ -19,6 +19,7 @@
 import org.springframework.cloud.stream.provisioning.ProducerDestination;
 
 /**
+ * A producer destination for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubProducerDestination.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorTests.java [hunk 32]
```diff
@@ -35,6 +35,9 @@
 		AbstractBinderTests<PubSubTestBinder, ExtendedConsumerProperties<PubSubConsumerProperties>,
 				ExtendedProducerProperties<PubSubProducerProperties>> {
 
+	/**
+	 * the emulator.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinderEmulatorTests.java]: "The emulator instance, shared across tests"

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinderTests.java [hunk 33]
```diff
@@ -32,6 +32,7 @@
 import static org.mockito.Mockito.verify;
 
 /**
+ * Tests for channel binder.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinderTests.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubTestBinder.java [hunk 34]
```diff
@@ -44,6 +44,7 @@
 import org.springframework.context.support.GenericApplicationContext;
 
 /**
+ * Test binder for Pub/Sub.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubTestBinder.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubExtendedBindingsPropertiesTests.java [hunk 35]
```diff
@@ -52,6 +52,10 @@
 import static org.mockito.ArgumentMatchers.anyString;
 import static org.mockito.Mockito.when;
 
+/**
+ * Tests for extended binding properties.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/properties/PubSubExtendedBindingsPropertiesTests.java]: newline

File: spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java [hunk 36]
```diff
@@ -42,6 +42,7 @@
 import static org.mockito.Mockito.when;
 
 /**
+ * Tests for Pub/Sub provisioner.
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub-stream-binder/src/test/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisionerTests.java]: newline

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java [hunk 37]
```diff
@@ -61,6 +62,9 @@
 	/**
 	 * This constructor instantiates TopicAdminClient and SubscriptionAdminClient with all their
 	 * defaults and the provided credentials provider.
+	 * @param credentialsProvider the credentials provider to use
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java]: swap order

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java [hunk 38]
```diff
@@ -136,6 +140,8 @@ public void deleteTopic(String topicName) {
 	 * Return every topic in a project.
 	 *
 	 * <p>If there are multiple pages, they will all be merged into the same result.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java]: no newline because it's a method. While you are there, can you remove the newline before <p>?

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java [hunk 39]
```diff
@@ -255,6 +261,8 @@ public void deleteSubscription(String subscriptionName) {
 	 * Return every subscription in a project.
 	 *
 	 * <p>If there are multiple pages, they will all be merged into the same result.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java]: same, no newline

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java [hunk 40]
```diff
@@ -264,6 +272,8 @@ public void deleteSubscription(String subscriptionName) {
 	}
 
 	/**
+	 * Get the default ack deadline.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/PubSubAdmin.java]: no newline

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/subscriber/PubSubSubscriberOperations.java [hunk 41]
```diff
@@ -44,7 +44,13 @@
 public interface PubSubSubscriberOperations {
 
 	/**
+	 * Subscribe to a subscription with a given message receiver.
+	 *
 	 * @deprecated as of 1.1, use {@link #subscribe(String, Consumer)} instead.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/subscriber/PubSubSubscriberOperations.java]: no newline

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultPublisherFactory.java [hunk 42]
```diff
@@ -78,6 +79,8 @@ public DefaultPublisherFactory(GcpProjectIdProvider projectIdProvider) {
 	/**
 	 * Set the provider for the executor that will be used by the publisher. Useful to specify the number of threads to
 	 * be used by each executor.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultPublisherFactory.java]: no newlines in method javadoc -- several in this file

File: spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultSubscriberFactory.java [hunk 43]
```diff
@@ -90,34 +91,44 @@ public String getProjectId() {
 	/**
 	 * Set the provider for the subscribers' executor. Useful to specify the number of threads to be
 	 * used by each executor.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultSubscriberFactory.java]: no newlines in method javadoc -- several in this file

File: spring-cloud-gcp-samples/spring-cloud-gcp-config-sample/src/test/java/com/example/ApplicationTests.java [hunk 44]
```diff
@@ -33,6 +33,7 @@
 import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
 
 /**
+ * Test for config sample.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-config-sample/src/test/java/com/example/ApplicationTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Album.java [hunk 45]
```diff
@@ -22,6 +22,7 @@
 import org.springframework.cloud.gcp.data.datastore.core.mapping.Entity;
 
 /**
+ * Sample entity.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Album.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/ConvertersExample.java [hunk 46]
```diff
@@ -25,6 +25,7 @@
 import org.springframework.core.convert.converter.Converter;
 
 /**
+ * Converters for sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/ConvertersExample.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java [hunk 47]
```diff
@@ -32,6 +32,7 @@
 import org.springframework.context.annotation.Bean;
 
 /**
+ * Sample app for Datastore repository.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/DatastoreRepositoryExample.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Singer.java [hunk 48]
```diff
@@ -30,6 +30,7 @@
 import org.springframework.data.annotation.Id;
 
 /**
+ * Sample entity.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Singer.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SingerRepository.java [hunk 49]
```diff
@@ -19,6 +19,7 @@
 import org.springframework.cloud.gcp.data.datastore.repository.DatastoreRepository;
 
 /**
+ * Sample repository for app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/SingerRepository.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/test/java/com/example/ApplicationTests.java [hunk 50]
```diff
@@ -49,15 +49,12 @@
...
- * @author Chengyuan Zhao
- * @author Dmitry Solomakha
- */
-
-/*
  * This tests verifies that the datastore-sample works. In order to run it, use the
  *
  * -Dit.datastore=true -Dspring.cloud.gcp.sql.database-name=[...]
  * -Dspring.cloud.gcp.datastore.namespace=[...]
+ * @author Chengyuan Zhao
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/test/java/com/example/ApplicationTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/DemoApplication.java [hunk 51]
```diff
@@ -26,6 +26,10 @@
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 import org.springframework.context.annotation.Bean;
 
+/**
+ * Sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/DemoApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/House.java [hunk 52]
```diff
@@ -20,6 +20,10 @@
 import javax.persistence.GeneratedValue;
 import javax.persistence.Id;
 
+/**
+ * A house entity for the sample application.
+ * @author Joao Andre Martins
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/House.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/HouseRepository.java [hunk 53]
```diff
@@ -18,6 +18,10 @@
 
 import org.springframework.data.repository.CrudRepository;
 
+/**
+ * A sample repository for House entities.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample/src/main/java/com/example/HouseRepository.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/SpannerExampleDriver.java [hunk 54]
```diff
@@ -28,6 +28,10 @@
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.Profile;
 
+/**
+ * Application to execute the sample app for Spanner.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/SpannerExampleDriver.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/SpannerTemplateExample.java [hunk 55]
```diff
@@ -30,8 +30,10 @@
 import org.springframework.stereotype.Component;
 
 /**
+ * Example usage of the Spanner Template.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/SpannerTemplateExample.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/TradeRepository.java [hunk 56]
```diff
@@ -26,6 +26,7 @@
 import org.springframework.data.rest.core.annotation.RepositoryRestResource;
 
 /**
+ * A sample repository.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/TradeRepository.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/Trader.java [hunk 57]
```diff
@@ -21,6 +21,7 @@
 import org.springframework.cloud.gcp.data.spanner.core.mapping.Table;
 
 /**
+ * A sample entity.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/Trader.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/TraderRepository.java [hunk 58]
```diff
@@ -20,6 +20,7 @@
 import org.springframework.data.rest.core.annotation.RepositoryRestResource;
 
 /**
+ * A sample repository.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/main/java/com/example/TraderRepository.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/test/java/com/example/SpannerRepositoryTests.java [hunk 59]
```diff
@@ -45,6 +45,10 @@
 import static org.hamcrest.Matchers.is;
 import static org.junit.Assume.assumeThat;
 
+/**
+ * Tests the Spanner repository example.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/test/java/com/example/SpannerRepositoryTests.java]: newline, "Tests for"

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/test/java/com/example/SpannerTemplateTests.java [hunk 60]
```diff
@@ -38,6 +38,10 @@
 import static org.hamcrest.Matchers.is;
 import static org.junit.Assume.assumeThat;
 
+/**
+ * Tests for the Spanner template usage.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-sample/src/test/java/com/example/SpannerTemplateTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/java/com/example/PubSubJsonPayloadApplicationTests.java [hunk 61]
```diff
@@ -38,6 +38,10 @@
 import static org.hamcrest.CoreMatchers.is;
 import static org.junit.Assume.assumeThat;
 
+/**
+ * Tests the Pub/Sub Json payload app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample/src/test/java/com/example/PubSubJsonPayloadApplicationTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/java/com/example/WebController.java [hunk 62]
```diff
@@ -22,7 +22,9 @@
 import org.springframework.web.servlet.view.RedirectView;
 
 /**
+ * Web app for sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/java/com/example/WebController.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java [hunk 63]
```diff
@@ -35,15 +35,11 @@
 import static org.junit.Assume.assumeThat;
 
 /**
+ * This tests verifies that the pubsub-integration-sample works.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-test/src/test/java/com/example/SampleAppIntegrationTest.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/main/java/com/example/GcsSpringIntegrationApplication.java [hunk 64]
```diff
@@ -43,8 +43,10 @@
 import org.springframework.messaging.MessageHandler;
 
 /**
+ * Storage Spring Integration sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/main/java/com/example/GcsSpringIntegrationApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/test/java/com/example/GcsSpringIntegrationTests.java [hunk 65]
```diff
@@ -54,6 +54,7 @@
  *
  * To run this test locally, first specify the buckets and local directory used by sample in
  * java/com/example/resources/application.properties. Then, run: mvn -Dit.storage=true test.
+ * @author Daniel Zougi
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/test/java/com/example/GcsSpringIntegrationTests.java]: cat on keyboard alert

File: spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/test/java/com.example/LoggingSampleApplicationTests.java [hunk 66]
```diff
@@ -49,6 +49,10 @@
 import static org.hamcrest.Matchers.is;
 import static org.junit.Assume.assumeThat;
 
+/**
+ * Tests for the logging sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/src/test/java/com.example/LoggingSampleApplicationTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/PubSubBinderApplication.java [hunk 67]
```diff
@@ -20,6 +20,7 @@
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
 /**
+ * Sample application for a binder.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/PubSubBinderApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SinkExample.java [hunk 68]
```diff
@@ -24,6 +24,7 @@
 import org.springframework.cloud.stream.messaging.Sink;
 
 /**
+ * Example of a sink for the sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SinkExample.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SourceExample.java [hunk 69]
```diff
@@ -27,6 +27,7 @@
 import org.springframework.web.bind.annotation.RestController;
 
 /**
+ * An example source for the sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SourceExample.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/UserMessage.java [hunk 70]
```diff
@@ -19,6 +19,7 @@
 import java.time.LocalDateTime;
 
 /**
+ * A user message for the sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/UserMessage.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/test/java/com/example/SampleAppIntegrationTest.java [hunk 71]
```diff
@@ -39,15 +39,11 @@
 import static org.junit.Assume.assumeThat;
 
 /**
+ * This tests verifies that the pubsub-binder-sample works.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/test/java/com/example/SampleAppIntegrationTest.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/PubSubApplication.java [hunk 72]
```diff
@@ -19,6 +19,10 @@
 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
+/**
+ * Pub/Sub sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/PubSubApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/WebController.java [hunk 73]
```diff
@@ -35,6 +35,10 @@
 import org.springframework.web.bind.annotation.RestController;
 import org.springframework.web.servlet.view.RedirectView;
 
+/**
+ * Web app for Pub/Sub sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/main/java/com/example/WebController.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/test/java/com/example/PubSubApplicationTests.java [hunk 74]
```diff
@@ -56,6 +56,10 @@
 import static org.hamcrest.Matchers.is;
 import static org.junit.Assume.assumeThat;
 
+/**
+ * Tests for the Pub/Sub sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/src/test/java/com/example/PubSubApplicationTests.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/java/com/example/SqlApplication.java [hunk 75]
```diff
@@ -20,7 +20,9 @@
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
 /**
+ * Sample application for MySQL.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/java/com/example/SqlApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/java/com/example/WebController.java [hunk 76]
```diff
@@ -24,7 +24,9 @@
 import org.springframework.web.bind.annotation.RestController;
 
 /**
+ * Web app controller class for sample application. Contains a function that runs a query and displays the results.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/java/com/example/WebController.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/main/java/com/example/SqlApplication.java [hunk 77]
```diff
@@ -20,6 +20,7 @@
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
 /**
+ * Sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/main/java/com/example/SqlApplication.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/main/java/com/example/WebController.java [hunk 78]
```diff
@@ -24,6 +24,7 @@
 import org.springframework.web.bind.annotation.RestController;
 
 /**
+ * Web app controller for sample app.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample/src/main/java/com/example/WebController.java]: newline

File: spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample/src/main/java/com/example/Application.java [hunk 79]
```diff
@@ -20,6 +20,7 @@
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
 /**
+ * Sample application.
```
Comment (elefeint) [inline spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample/src/main/java/com/example/Application.java]: newline

File: spring-cloud-gcp-security-iap/src/test/java/org/springframework/cloud/gcp/security/iap/AudienceValidatorTests.java [hunk 80]
```diff
@@ -76,6 +79,9 @@ public void testWrongAudienceDoesNotMatch() {
 		});
 	}
 
+	/**
+	 * Configuration for the  tests.
```
Comment (elefeint) [inline spring-cloud-gcp-security-iap/src/test/java/org/springframework/cloud/gcp/security/iap/AudienceValidatorTests.java]: extra space before "tests"

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 81]
```diff
@@ -36,10 +36,15 @@
  * @author Vinicius Carvalho
  * @author Artem Bilan
  * @author Mike Eltsufin
+ * @author Chengyuan Zhao
+ *
```
Comment (elefeint) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: no newline

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java [hunk 82]
```diff
@@ -108,6 +108,9 @@ public GoogleStorageResource(Storage storage, String location,
 
 	/**
 	 * Constructor that defaults autoCreateFiles to true.
+	 *
```
Comment (elefeint) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java]: no newline

File: spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/config/GoogleConfigEnvironment.java [hunk 83]
```diff
@@ -53,6 +54,9 @@ void setVariables(List<Variable> variables) {
 		return config;
 	}
 
+	/**
+	 * A data object for a configuration.
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/config/GoogleConfigEnvironment.java]: I tried for many cases to write more descriptive lines but I can't really be sure if they're actually accurate without context.

File: spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfiguration.java [hunk 84]
```diff
@@ -80,6 +82,7 @@ public GcpProjectIdProvider gcpProjectIdProvider() {
 	 * Provides default implementation for determining GCP environment.
 	 * Can be overridden to avoid interacting with real environment.
 	 * @since 1.1
+	 * @return a GCP envornment provider
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfiguration.java]: will fix

File: spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/datastore/DatastoreTransactionManagerAutoConfiguration.java [hunk 85]
```diff
@@ -41,6 +41,9 @@
 @AutoConfigureBefore(TransactionAutoConfiguration.class)
 public class DatastoreTransactionManagerAutoConfiguration {
 
+	/**
+	 * Configuration class.
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/datastore/DatastoreTransactionManagerAutoConfiguration.java]: This one is simply following the form of other Spring Data modules' transaction manager configs to be honest. I don't think it actually needs to be in an inner class here.

File: spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/logging/extractors/XCloudTraceIdExtractor.java [hunk 86]
```diff
@@ -25,6 +25,9 @@
  */
 public class XCloudTraceIdExtractor implements TraceIdExtractor {
 
+	/**
+	 * The name of the header that contains the trade id.
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/logging/extractors/XCloudTraceIdExtractor.java]: will fix

File: spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/logging/StackdriverJsonLayoutLoggerTests.java [hunk 87]
```diff
@@ -30,6 +30,7 @@
 import static org.assertj.core.api.Assertions.assertThat;
 
 /**
+ * Tests the Stackdriver Json Layout Logger.
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/logging/StackdriverJsonLayoutLoggerTests.java]: I think this should be fine; it makes sense and isn't flagrantly wrong. It will be a scary day when robotic code style starts creeping into human language.

**Comment by ChengyuanZhao** [comment]
@elefeint changes made, PTAL. (though I didn't totally change all the cases of makes-sense but not-identical sentences)

**Comment by ChengyuanZhao** [comment]
@elefeint thanks so much :D !
