### PR TITLE
Datastore - support custom maps

### LINKED ISSUE #2334: Custom Subclasses of Map Cannot be Stored
This section of TwoStepsConversion.java:
```java
	private Value convertOnWrite(Object proppertyVal, EmbeddedType embeddedType,
			String fieldName, TypeInformation typeInformation) {
		Object val = proppertyVal;

		Function<Object, Value> writeConverter = this::convertOnWriteSingle;
		if (proppertyVal != null) {
			switch (embeddedType) {
			case EMBEDDED_MAP:
				writeConverter = (x) -> convertOnWriteSingleEmbeddedMap(x, fieldName,
						(TypeInformation) typeInformation.getTypeArguments().get(1));
				break;
			case EMBEDDED_ENTITY:
				writeConverter = (x) -> convertOnWriteSingleEmbedded(x, fieldName);
				break;
			case NOT_EMBEDDED:
				writeConverter = this::convertOnWriteSingle;
				break;
			default:
				throw new DatastoreDataException(
						"Unexpected property embedded type: " + embeddedType);
			}
		}

		val = ValueUtil.toListIfArray(val);

		if (val instanceof Iterable) {
			List<Value<?>> values = new ArrayList<>();
			for (Object propEltValue : (Iterable) val) {
				values.add(writeConverter.apply(propEltValue));
			}
			return ListValue.of(values);
		}
		return writeConverter.apply(val);
	}
```

Attempts to obtain type arguments from Maps. However, my custom subclass has no type arguments. It throws the following exception:
```
java.lang.IndexOutOfBoundsException: Index: 1

	at java.base/java.util.Collections$EmptyList.get(Collections.java:4481)
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.lambda$convertOnWrite$2(TwoStepsConversions.java:261)
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnWrite(TwoStepsConversions.java:284)
	at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnWrite(TwoStepsConversions.java:247)
	at org.springframework.cloud.gcp.data.datastore.core.convert.DefaultDatastoreEntityConverter.lambda$write$3(DefaultDatastoreEntityConverter.java:183)
	at org.springframework.cloud.gcp.data.datastore.core.mapping.DatastorePersistentEntityImpl.lambda$doWithColumnBackedProperties$0(DatastorePersistentEntityImpl.java:206)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:355)
	at org.springframework.cloud.gcp.data.datastore.core.mapping.DatastorePersistentEntityImpl.doWithColumnBackedProperties(DatastorePersistentEntityImpl.java:203)
	at org.springframework.cloud.gcp.data.datastore.core.convert.DefaultDatastoreEntityConverter.write(DefaultDatastoreEntityConverter.java:175)
	at org.springframework.cloud.gcp.data.datastore.core.convert.DefaultDatastoreEntityConverter.write(DefaultDatastoreEntityConverter.java:55)
	at org.springframework.cloud.gcp.data.datastore.core.DatastoreTemplate.convertToEntityForSave(DatastoreTemplate.java:446)
	at org.springframework.cloud.gcp.data.datastore.core.DatastoreTemplate.getEntitiesForSave(DatastoreTemplate.java:163)
	at org.springframework.cloud.gcp.data.datastore.core.DatastoreTemplate.saveEntities(DatastoreTemplate.java:172)
	at org.springframework.cloud.gcp.data.datastore.core.DatastoreTemplate.save(DatastoreTemplate.java:147)
	at org.springframework.cloud.gcp.data.datastore.repository.support.SimpleDatastoreRepository.save(SimpleDatastoreRepository.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
```

### PR DESCRIPTION
**Pull request by dmitry-s**
fixes #2334

### CODE REVIEW

**Comment by ashesfall** [comment]
This is the second merge request resulting from requests I have made. That leads me to wonder if it is possible for me to become a contributor to this project. Is there a process in place?

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreEntityConverter.java [hunk 1]
```diff
@@ -42,15 +42,16 @@
...
 	 * @param entity the entity from Cloud Datastore.
-	 * @param <T> the type of the key in the map
-	 * @param <R> the type of the value in the map
+	 * @param typeInformation the actual type of the map
 	 * @return a Map where the key values are the field names and the values the field
 	 * values.
 	 */
 	<T, R> Map<T, R> readAsMap(Class<T> keyType, TypeInformation<R> componentType,
-			BaseEntity entity);
+			BaseEntity entity, TypeInformation typeInformation);
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DatastoreEntityConverter.java:56]: 1. Technically, it's a breaking change. Can we just overload with a new method that has an additional argument?
This especially seems to make sense because you sometimes call the method with `null` `typeInformation`.
2. Also, can we rename `typeInformation` to `mapTypeInformation`?
3. If you're getting the type information for the whole map, why do you need the key and value type information? Maybe it would be easier if the caller just passed the map they wanted to fill with results?

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DefaultDatastoreEntityConverter.java [hunk 2]
```diff
@@ -79,11 +81,23 @@ public ReadWriteConversions getConversions() {
...
-			BaseEntity entity) {
+			BaseEntity entity, TypeInformation typeInformation) {
 		if (entity == null) {
 			return null;
 		}
-		Map<T, R> result = new HashMap<>();
+		Object customMap = null;
+		if (typeInformation != null && !typeInformation.getType().isInterface()) {
+			try {
+				customMap = ((Constructor<?>) typeInformation.getType().getConstructor()).newInstance();
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DefaultDatastoreEntityConverter.java:91]: This just doesn't seem right. Can we put the burden on the caller to create the map?

**Comment by meltsufin** [comment]
@ashesfall We welcome contributions! All you have to do is open a pull request.
Here's [contributor guide](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc).

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DefaultDatastoreEntityConverter.java (hunk 2 above)
Comment (dmitry-s) [reply spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DefaultDatastoreEntityConverter.java:91]: Could you elaborate why it doesn't seem right?

Comment (ashesfall) [reply spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/convert/DefaultDatastoreEntityConverter.java:91]: I think if the caller has to create it, it will perhaps be inconsistent with the other cases.
