### PR TITLE
Firestore - switch to commit to avoid write limitations

### LINKED ISSUE #2561: FirestoreIntegrationTests.saveAllBulkTest » StatusRuntime INVALID_ARGUMENT
This is happening in CI, albeit not consistently.

### LINKED ISSUE #2574: Firestore - io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED
Getting an exception if the number of writes is increased to 100000 in FirestoreIntegrationTests.saveAllBulkTest.

### PR DESCRIPTION
**Pull request by dmitry-s**
fixes #2561 
fixes #2574

### CODE REVIEW

File: spring-cloud-gcp-data-firestore/src/main/java/org/springframework/cloud/gcp/data/firestore/FirestoreTemplate.java [hunk 1]
```diff
@@ -209,9 +211,17 @@ public boolean isUsingStreamTokens() {
 				return Flux.from(instances).doOnNext(t -> writes.add(createUpdateWrite(t)));
 			}
 
-			Flux<List<T>> inputs = Flux.from(instances).bufferTimeout(this.writeBufferSize, this.writeBufferTimeout);
-			return ObservableReactiveUtil.streamingBidirectionalCall(
-					this::openWriteStream, inputs, this::buildWriteRequest);
+			return Flux.from(instances).bufferTimeout(this.writeBufferSize, this.writeBufferTimeout)
```
Comment (meltsufin) [inline spring-cloud-gcp-data-firestore/src/main/java/org/springframework/cloud/gcp/data/firestore/FirestoreTemplate.java:214]: Can we de-dup this and the block in `deleteDocumentsByName()` by wrapping `builder.addWrites(createUpdateWrite(e))` into a lambda?

**Review by meltsufin — CHANGES_REQUESTED** [review]
Have you compared the performance difference?

**Comment by dmitry-s** [comment]
@meltsufin there is actually nothing to compare, the old way was unable to write more than a couple of thousands - that's why I thought it was faster.

**Review by meltsufin — APPROVED** [review]

**Review by elefeint — APPROVED** [review]
