### PR TITLE
Datastore Enum Query Method params

### LINKED ISSUE #1166: Allow enums as arguments in query methods
Could you please make possible use enums as arguments in query methods.
For example, we have a model:

```
Entity(name = "singers")
public class Singer {

    @Id
    @Field(name = "singer_id")
    private String singerId;

    @Field(name = "sex")
    private Sex sex; //enum
}
```

Datastore repository has a simple search method:

```
public interface SingerRepository extends DatastoreRepository<Singer, String> {
    Collection<Singer> findBySex(Sex sex);
}
```
An exception occurs after executing this method. Searching by string works fine. 
Enum arguments can be emulated with [name()](https://docs.oracle.com/javase/10/docs/api/java/lang/Enum.html#name()) method.

```

Caused by: org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class com.example.Sex to Datastore supported type.
	at org.springframework.cloud.gcp.data.datastore.core.convert.DatastoreNativeTypes.wrapValue(DatastoreNativeTypes.java:105) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.lambda$applySelectWithFilter$1(PartTreeDatastoreQuery.java:190) ~[spring-cloud-gcp-data-datastore-1.1.0.BUILD-20181031.173949-140.jar:1.1.0.BUILD-SNAPSHOT]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
```

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #1166

support enums in Query Methods

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@dmitry-s @meltsufin PTAL. To support this we only needed to add a mapping method or two to the maps we already had.

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 1]
```diff
@@ -235,13 +237,14 @@ boolean isNonEntityReturnedType(Class returnedType) {
 		}
 		for (int i = 0; i < tags.size(); i++) {
 			Object val = vals[i];
-			if (!GQL_PARAM_BINDING_FUNC_MAP.containsKey(val.getClass())) {
+			Class valClass = val.getClass().isEnum() ? Enum.class : val.getClass();
```
Comment (dmitry-s) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: maybe create a util method for that?

Comment (ChengyuanZhao) [reply spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Done, PTAL !
