### PR TITLE
Fix auditing when running through DatastoreTemplate.performTransaction

### LINKED ISSUE #2603: Auditing doesn't work on entities in Datastore when running through DatastoreTemplate.performTransaction()
When using `DatastoreTemplate.performTransaction()` with `spring-cloud-gcp-data-datastore` `1.2.6.RELEASE`, auditing doesn't work for entities.

That's because [the new `DatastoreTemplate` instance created in `performTransaction()`](https://github.com/spring-cloud/spring-cloud-gcp/blob/v1.2.6.RELEASE/spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplate.java#L435-L440) does not have the `ApplicationEventPublisher` of the original one, which is the mechanism by which the `AuditingHandler` eventually gets called to set the auditing properties.

I've [added a test to `DatastoreTemplateAuditingTests` in my fork](https://github.com/spring-cloud/spring-cloud-gcp/compare/master...fpavageau:bug-auditing-transaction) which demonstrates the problem.

I also have a [simple fix ready](https://github.com/spring-cloud/spring-cloud-gcp/compare/master...fpavageau:bugfix-auditing-transaction), if it's actually a bug and you want a PR.

### PR DESCRIPTION
**Pull request by fpavageau**
The new `DatastoreTemplate` instance should have the same
`ApplicationEventPublisher` as the original one, so that `AuditingHandler`
can be called.

Fixes #2603

### CODE REVIEW

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java [hunk 1]
```diff
@@ -82,6 +84,20 @@ public void testModifiedPrevProperties() {
 		this.datastoreTemplate.saveAll(Collections.singletonList(testEntity));
 	}
 
+	@Test
+	public void testInTransaction() {
+		when(datastore.runInTransaction(any()))
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java:89]: I see mock setup all done in `datastoreTemplate()`. Would it make sense to move it there?

**Review by meltsufin — CHANGES_REQUESTED** [review]
Generally, looks good!
Feel free to add yourself as `@author` on the files you touched.
Thanks!!

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java (hunk 1 above)
Comment (fpavageau) [reply spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java:89]: Personally, I prefer keeping the specific setup where it's actually used, and Mockito could complain about unnecessary setup in the other tests, depending on its configuration. However, I've tested moving the code and it works, so Mockito is not in strict mode and the code can be arranged however you prefer.

Comment (meltsufin) [reply spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java:89]: I don't feel strongly either way. I'm also not sure it's good that the verification is outside the test method, but that's a problem for another time. :)

**Comment by meltsufin** [comment]
@fpavageau   BTW, no need to squash or force-push in branches/PRs because we always squash commits on merge to master. Do you want to add your name to `DatastoreTemplate.java`? If not, I'm happy to merge.

File: spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java (hunk 1 above)
Comment (fpavageau) [reply spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java:90]: OK, I think I'll leave it that way then, not specifying every possible behavior for all the tests.

I agree the verification in an `Answer` is brittle, which is when I first ran the test, without the added behavior on the mock, it passed: the `Datastore.put()` method was never called! We could extract an assertion method which would use an `ArgumentCaptor` to verify the call and its parameter, instead. However it's not the only occurence in the project of assertions in `Answer`s, so just fixing this one instance probably doesn't really make sense.

Comment (meltsufin) [reply spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplateAuditingTests.java:90]: Yeah, no need to address that here.

**Comment by fpavageau** [comment]
I added my name to the test class, I guess that's enough.

**Review by meltsufin — APPROVED** [review]
