### PR TITLE
removes dependency on javax.xml.bind

### LINKED ISSUE #400: ./mvnw clean install fails to build on java 9
Error comes from `GoogleConfigEnvironment` in the autoconfigure module during build (javadoc phase?):

````
 ./mvnw clean install
[INFO] Spring Cloud GCP Autoconfigure Module .............. FAILURE [ 17.731 s]
Because: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (javadoc) on project spring-cloud-gcp-autoconfigure: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /Users/<me>/dev/proj/spring-cloud-gcp/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/config/GoogleConfigEnvironment.java:24: error: package javax.xml.bind is not visible
[ERROR] import javax.xml.bind.DatatypeConverter;
[ERROR] ^
`````

Directions we can go towards:
 - state that we don't support java 9
 - add java.xml.bind module to the mvnw script 
...

### PR DESCRIPTION
**Pull request by dmitry-s**
Fixes #400 

javax.xml.bind.DatatypeConverter was moved to a separate module in java 9 and also has been deprecated

### CODE REVIEW

File: spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/config/GoogleConfigEnvironmentTest.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+  @Test
+  public void testSetVariabeValue() {
+    GoogleConfigEnvironment.Variable var = new Variable();
+    String value = "v a l u e";
+    String encodedString = Base64.getEncoder().encodeToString(value.getBytes());
+    var.setValue(encodedString);
+    assertEquals(value, var.getValue());
+  }
+}
```
Comment (joaoandremartins) [inline spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/config/GoogleConfigEnvironmentTest.java]: New line
