### PR TITLE
Evaluate consumer group settings in the Pub/Sub binder

### LINKED ISSUE #422: evaluate the consumer group settings in the pub-sub binder
For the spring binder you can configure a group so you can have multiple subscriptions for one topic.

This feature does not work currently, because the group name is not taken into consideration.

### PR DESCRIPTION
**Pull request by Andy2003**
Fixes #422.

### CODE REVIEW

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java [hunk 1]
```diff
@@ -54,19 +54,25 @@ public ProducerDestination provisionProducerDestination(String name,
 	public ConsumerDestination provisionConsumerDestination(String name, String group,
 			ExtendedConsumerProperties<PubSubConsumerProperties> properties)
 			throws ProvisioningException {
-		if (this.pubSubAdmin.getSubscription(name) == null) {
+		return new PubSubConsumerDestination(name);
+	}
+
+	public String createSubscription(String name, String group,
```
Comment (joaoandremartins) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: Why the extra method?
Shouldn't this work be done in `provisionProducerDestination` like before, but considering the group name instead of just `name`?

Comment (Andy2003) [reply spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: before this change `provisionConsumerDestination` was called 2 times:

1. `org.springframework.cloud.stream.binder.AbstractMessageChannelBinder#doBindConsumer` 
2. `org.springframework.cloud.gcp.stream.binder.pubsub.PubSubMessageChannelBinder#createConsumerEndpoint`

This resulted in wrong destination names.

Comment (Andy2003) [reply spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: I Removed the second invocation so that the PubSubConsumerDestination now directly identifies the subscription to be used

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java [hunk 2]
```diff
@@ -57,24 +57,16 @@ public PubSubMessageChannelBinder(String[] headersToEmbed,
 	@Override
 	protected MessageHandler createProducerMessageHandler(ProducerDestination destination,
 			ExtendedProducerProperties<PubSubProducerProperties> producerProperties,
-			MessageChannel errorChannel) throws Exception {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java]: I think you can revert changes to this file since they're just cosmetic?

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java [hunk 3]
```diff
@@ -57,24 +57,16 @@ public PubSubMessageChannelBinder(String[] headersToEmbed,
...
 	}
 
 	@Override
 	protected MessageProducer createConsumerEndpoint(ConsumerDestination destination, String group,
-			ExtendedConsumerProperties<PubSubConsumerProperties> properties) throws Exception {
-
-		String consumerName = group == null
-				? destination.getName() : destination.getName() + "-" + group;
-
-		this.provisioningProvider.provisionConsumerDestination(
```
Comment (joaoandremartins) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java]: Why are we removing this?
We still want to auto-create subscriptions, right?

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java (hunk 1 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: Not sure if I understand?
We were calling `provisionProducerDestination` once, to automatically create the topic, and `provisionConsumerDestination` once, to create the subscription.

It sounds to me we still need both of those calls.

Comment (joaoandremartins) [reply spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: I realised that `provisionProducerDestination` is also called by `AbstractMessageChannelBinder.doBindProducer()`.

Should we also remove that call?

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java [hunk 4]
```diff
@@ -54,19 +54,20 @@ public ProducerDestination provisionProducerDestination(String name,
...
+				this.pubSubAdmin.createSubscription(subscription, name);
 			}
 			else {
-				throw new ProvisioningException("Unexisting '" + name + "' subscription.");
+				throw new ProvisioningException("Unexisting '" + subscription + "' subscription.");
 			}
 		}
-
-		return new PubSubConsumerDestination(name);
+		return  new PubSubConsumerDestination(subscription);
```
Comment (joaoandremartins) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java]: Nit: 2 spaces between `return` and `new`.

File: spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java [hunk 5]
```diff
@@ -57,24 +57,16 @@ public PubSubMessageChannelBinder(String[] headersToEmbed,
 	@Override
 	protected MessageHandler createProducerMessageHandler(ProducerDestination destination,
 			ExtendedProducerProperties<PubSubProducerProperties> producerProperties,
-			MessageChannel errorChannel) throws Exception {
+			MessageChannel errorChannel) {
 
-		this.provisioningProvider.provisionProducerDestination(
-				destination.getName(), producerProperties);
+		this.provisioningProvider.provisionProducerDestination(destination.getName(), producerProperties);
```
Comment (joaoandremartins) [inline spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub/PubSubMessageChannelBinder.java]: This is also being called twice.
Should we remove it as part of this PR?

**Comment by joaoandremartins** [comment]
Adding tests to the binder is going to be a high priority, as part of #292.
