### PR TITLE
Move SQL sample tests to be under 1 database

### LINKED ISSUE #1125: Move cloud SQL sample tests to same Database
As a followup to #1123, it would be ideal to remove `application-test.properties` files and move all properties set by integration tests to travis.yml. This way we do not provide users with tests that do not work out of the box.

### PR DESCRIPTION
**Pull request by dzou**
This moves the SQL sample tests to a single database under the spring-cloud-gcp-ci project.

The purpose of doing this is to have the properties be set in travis.yml and have the tests inherit from the `application.properties` that users modify. This way allows the tests to work for users who want to try out the test.

Fixes #1125.

### CODE REVIEW

File: spring-cloud-gcp-samples/spring-cloud-gcp-sql-sample/src/test/java/com/example/SqlApplicationTests.java [hunk 1]
```diff
@@ -28,28 +28,27 @@
...
- * Run with: mvn -Dit.cloudsql -Dspring.cloud.gcp.sql.database-name=[...]
- * -Dspring.cloud.gcp.sql.instance-connection-name=[...]
- * -Dspring.datasource.password=[...] test
+ * Run with: mvn -Dit.cloudsql test
  *
  * @author Daniel Zou
  */
 @RunWith(SpringRunner.class)
-@TestPropertySource("classpath:application-test.properties")
+@PropertySource("classpath:application.properties")
```
Comment (meltsufin) [inline spring-cloud-gcp-samples/spring-cloud-gcp-sql-sample/src/test/java/com/example/SqlApplicationTests.java]: I think you can omit this line altogether.
