### PR TITLE
Gh 210 buckets resources

### LINKED ISSUE #210: .exists() throws exception for existing GCS buckets
https://github.com/spring-cloud/spring-cloud-gcp/blob/9debe0aff000396f67045c17e3b70fc056ebcd3c/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java#L109

throws ``java.lang.StringIndexOutOfBoundsException: String index out of range: -1``

when used with a bucket name that exists.

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #210

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@artembilan @meltsufin I can't add reviewers/ assign myself to PRs and issues for this repo until I'm added as a collaborator. In the meantime, please add take a look and add yourself as reviewers?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+import com.google.cloud.storage.Storage;
+
+import org.springframework.core.io.Resource;
+import org.springframework.core.io.WritableResource;
+import org.springframework.util.Assert;
+
+/**
+ * Implements {@link WritableResource} for buckets in Google Cloud Storage.
+ */
+public class GoogleStorageResourceBucket implements WritableResource {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: WritableResource not needed here?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java [hunk 2]
```diff
@@ -114,6 +115,12 @@ private Blob resolve() throws IOException {
 	}
 
 	private Blob createBlob() throws IOException {
+		// Creating the bucket resource will create the bucket if necessary.
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Unhelpful comment?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+	public OutputStream getOutputStream() throws IOException {
+		throw new UnsupportedOperationException(
+				"Cannot get output stream for a storage bucket.");
+	}
+
+	private Bucket resolve() {
+		return this.storage.get(this.bucketName);
+	}
+
+	private Bucket throwExceptionForNullBucket(Bucket bucket) throws IOException {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I know this code is copied and pasted, but should this method be called `getBucket()` instead?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+
+	public GoogleStorageResourceBucket(Storage storage, String bucketName,
+			boolean createBucketIfNotExists) {
+		Assert.notNull(storage, "Storage object can not be null");
+		Assert.notNull(bucketName, "Bucket name can not be null");
+
+		this.storage = storage;
+		this.bucketName = bucketName;
+
+		if (!exists() && createBucketIfNotExists) {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Can we do this elsewhere? I don't like this kind of advanced logic inside the constructor...

How about we create a `createBucketInGCS()` method?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+			this.storage.create(BucketInfo.newBuilder(this.bucketName).build());
+		}
+	}
+
+	@Override
+	public boolean exists() {
+		try {
+			return throwExceptionForNullBucket(resolve()).exists();
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Again, I know this is copy&pasted, but can we change this to call `resolve()` and check if the result is `null`?
That would spare us the unnecessary and costly exception handling.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+		catch (URISyntaxException e) {
+			throw new IOException("Invalid URI syntax", e);
+		}
+		return uri;
+	}
+
+	@Override
+	public File getFile() throws IOException {
+		throw new UnsupportedOperationException(
+				"Cannot get a file from a storage bucket.");
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Change message to something like "GCS bucket is not in the local file system"?

**Comment by ChengyuanZhao** [comment]
travis-ci had trouble starting up:

Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching repo1.maven.org found.

I'll close and reopen the PR to trigger a re-build

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 7]
```diff
@@ -0,0 +1,163 @@
...
+	@Override
+	public long lastModified() throws IOException {
+		throw new UnsupportedOperationException(
+				"Cannot get last-modified for a storage bucket.");
+	}
+
+	@Override
+	public Resource createRelative(String relativePath) throws IOException {
+		return new GoogleStorageResourceObject(this.storage,
+				getURI().toString() + (relativePath.startsWith("/") ? "" : "/")
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: What if the bucket URI already ends in a `/`?
We'd want to avoid cases like `gs://bucket//blob`, but we should also take this chance to fix the case where we can't create blobs on buckets that don't end in a `/`.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+						+ relativePath);
+	}
+
+	@Override
+	public String getFilename() {
+		try {
+			return throwExceptionForNullBucket(resolve()).getName();
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Ditto for unnecessary exception handling.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 3 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: On a second look, it looks like this method is even unnecessary due to my previous comments.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java [hunk 9]
```diff
@@ -114,6 +115,12 @@ private Blob resolve() throws IOException {
...
+		Resource bucket = getBucket();
+		if (!bucket.exists()) {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: I'd prefer to see another kind of logic here, like -- check if the bucket exists, if it doesn't, create it if you can (e.g. configuration allows) by calling an explicit `create()`-like method (not a constructor).

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java [hunk 10]
```diff
@@ -114,6 +115,12 @@ private Blob resolve() throws IOException {
...
+			throw new IOException("Unable to create blob: " + getBlobId().toString()
+					+ ", because the bucket does not exist: " + getBlobId().getBucket());
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Does `getBlobId().getBucket()` have the desired `toString()` effect?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 1 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I was thinking of keeping it there just so we can throw the unsupported operation exception along with the explanation string that it's a bucket resource. The reason being that the user will be using bucket path resources and object path resources in the same way, and if they inadvertently try to get an output stream or check isWriteable I would rather they get the unsupported operation exception with an explanation than a class casting exception because those two functions don't exist at all.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 4 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Will do.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 5 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Will do.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 6 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Yup will do.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: We don't store the entire bucket path in this class, just the bucket name. The reason is the GCS bucket functions all work on the bucket name, not the path. As a result, the path we construct here for the bucket will always not have the /.

Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Also, i've got a unit test for this case , too.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 8 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: This one is necessary, since resolve() might return null, and .getName() would then give an NPE.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java (hunk 2 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Will remove.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java (hunk 10 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Yes, the toString() gets the entire path to the blob , and the getBucket() just gets the bucket name.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 5 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Oh on second look, I had this here because resolve() might return null, and calling .exists() would then give an NPE.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 1 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Actually, the way things are now, the user needs to cast a `Resource` into a `WritableResource` to be able to write to it. In which case, the cast should actually just fail, instead of allowing it and then throwing UOE.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 11]
```diff
@@ -0,0 +1,158 @@
...
+
+	public GoogleStorageResourceBucket(Storage storage, String bucketName,
+			boolean createBucketIfNotExists) {
+		Assert.notNull(storage, "Storage object can not be null");
+		Assert.notNull(bucketName, "Bucket name can not be null");
+
+		this.storage = storage;
+		this.bucketName = bucketName;
+
+		createBucketIfRequired(createBucketIfNotExists);
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I actually meant not doing this in the constructor at all. Instead, the user can call `create()` if they want to create it explicitly, or we create it for them automatically in any appropriate methods (`createRelative()` is really the only one that comes to mind) if `createBucketIfNotExists` is `true`.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Yeah, I meant to ask about that -- do we really need them to work based on the name?
I'd rather have them work based on a `Bucket`, with `getName()` etc., unless there is a good reason not to.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 12]
```diff
@@ -84,7 +89,14 @@ public Resource resolve(String location, ResourceLoader resourceLoader) {
...
 				}
 			}
-			return new GoogleStorageResource(this.storage, location, this.settings.isAutoCreateFiles());
+
+			if (pathParts.length < 2) {
+				return new GoogleStorageResourceBucket(this.storage, bucketName,
+						this.settings.isAutoCreateFiles());
+			}
+
+			return new GoogleStorageResourceObject(this.storage, location,
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: I'm guessing we're letting the GCS API error out for malformed GCS URIs, like `gs://bucket-name/asdasd/asdasd/asdasd`. I think I'm fine with that.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 13]
```diff
@@ -0,0 +1,158 @@
...
+	public Resource createRelative(String relativePath) throws IOException {
+		return new GoogleStorageResourceObject(this.storage,
+				getURI().toString() + (relativePath.startsWith("/") ? "" : "/")
+						+ relativePath);
+	}
+
+	@Override
+	public String getFilename() {
+		Bucket bucket = resolve();
+		return bucket == null ? null : bucket.getName();
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: This could probably be improved if `bucket` were a non-nullable field.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java [hunk 14]
```diff
@@ -114,6 +115,11 @@ private Blob resolve() throws IOException {
 	}
 
 	private Blob createBlob() throws IOException {
+		Resource bucket = getBucket();
+		if (!bucket.exists()) {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Previous comment on logic change here still stands.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I actually think it's pretty clean to just have the bucket name as a string, and I would prefer to not have a Bucket that might refer to a nonexistent bucket on GCS. As it is now a GSRB is an object that refers to a potentially nonexistent bucket on GCS, and any actual Bucket we're using exists on GCS.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 11 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I think it's just a difference of opinion. I prefer doing it in the constructor, and we control it with the auto-create boolean argument.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 12 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Isn't `gs://bucket-name/asdasd/asdasd/asdasd` a valid path though?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 3 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: It is gone :)

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java (hunk 14 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Yea I just disagreed that comment. It feels pretty natural to me to have the constructor take care of creating the bucket or not based on the auto-create bool setting.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 12 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: You're right -- nevermind that!

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 11 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: It's more than just opinion.
The constructor should not contain extraneous logic that should belong in other methods. Later on this PR you're creating the file remotely in GCS by calling the constructor. I would not expect that as a Java developer.
There is no reason why the status of an object of this kind in memory should map to the status of the file in GCS. That's why methods like `exists()` exist.

It also makes unit testing objects of this kind a bummer.
That method should probably also throw an `IOException` in case the file couldn't be constructed, which is a code smell coming from a constructor.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: How is calling `resolve()` on every method that needs the bucket _cleaner_?

And again, no reason why the state of this Java object in memory should map to the state of the GCS entity it refers to IMO.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 15]
```diff
@@ -0,0 +1,158 @@
...
+			uri = new URI(GoogleStorageProtocolResolver.PROTOCOL + getFilename());
+		}
+		catch (URISyntaxException e) {
+			throw new IOException("Invalid URI syntax", e);
+		}
+		return uri;
+	}
+
+	@Override
+	public File getFile() throws IOException {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Sorry for bothering you with changes to pasted code, but the thrown `IOException` should also probably be changed to `UnsupportedOperationException`.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 16]
```diff
@@ -0,0 +1,158 @@
...
+	}
+
+	@Override
+	public long lastModified() throws IOException {
+		throw new UnsupportedOperationException(
+				"Cannot get last-modified for a storage bucket.");
+	}
+
+	@Override
+	public Resource createRelative(String relativePath) throws IOException {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Seems like this method actually doesn't throw an `IOException`?

Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: NVM -- that is part of the method signature.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Again, I think this is an opinion thing. I think it's conceptually much cleaner, and calling resolve 3 or 4 times in the class isn't messy in my opinion.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 11 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I really think your explanation still sounds just like your opinion. I can explain my perspective too:

- a user can create a GSRB setting the auto-create bool
- the user doesn't need to know if the bucket already exists: that's the whole point of the auto-create functionality. 
- the `exists` function works as expected

As a Java developer I think this is pretty simple and intuitive.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 15 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Ah my bad! Will fix.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I'll defer to what others think. @artembilan @meltsufin

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 11 above)
Comment (meltsufin) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: In the case of a GCS object resource we only create it when attempting to write to it. I don't see why it should be any different for a bucket resource. The "write" operation for a Bucket is `.createRelative()`. So, I think that's where the call to `createBucketIfRequired` belongs.

`GoogleStorageResourceBucket`, just like `java.util.File` is simply a handle to a resource that may or may not exist. So, auto-creation in the constructor doesn't make sense to me. I would also make `createBucketIfRequired` public.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 17]
```diff
@@ -0,0 +1,149 @@
...
+		return new GoogleStorageResourceObject(this.storage,
+				getURI().toString() + (relativePath.startsWith("/") ? "" : "/")
+						+ relativePath);
+	}
+
+	@Override
+	public String getFilename() {
+		Bucket bucket = resolve();
```
Comment (meltsufin) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: You already have `this.bucketName`. Why do `resolve()`?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 18]
```diff
@@ -0,0 +1,149 @@
...
+	}
+
+	@Override
+	public boolean exists() {
+		return resolve() != null;
+	}
+
+	@Override
+	public boolean isReadable() {
+		return false;
```
Comment (meltsufin) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Why `false`?

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 7 above)
Comment (meltsufin) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: See my other comment on `getFilename` which doesn't require a call to `resolve` and it also guarantees that there is no trailing `/`. So, as long as `getFilename` is fixed, simply using `this.bucketName`, this code is fine.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java (hunk 14 above)
Comment (meltsufin) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: If you're doing auto-create, it should be here, not in the constructor.

File: spring-cloud-gcp-storage/src/test/java/org/springframework/cloud/gcp/storage/GoogleStorageTests.java [hunk 19]
```diff
@@ -51,13 +53,73 @@
 	@Value("gs://test-spring/images/spring.png")
 	private Resource remoteResource;
 
+	@Value("gs://test-spring")
```
Comment (meltsufin) [inline spring-cloud-gcp-storage/src/test/java/org/springframework/cloud/gcp/storage/GoogleStorageTests.java]: Please also test
```
gs://
gs:///
```

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 20]
```diff
@@ -84,7 +89,14 @@ public Resource resolve(String location, ResourceLoader resourceLoader) {
 							+ "so defaults are used.");
 				}
 			}
-			return new GoogleStorageResource(this.storage, location, this.settings.isAutoCreateFiles());
+
+			if (pathParts.length < 2) {
```
[the remark this answers is not in the document]
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: gs://bucket/ would work fine, gs:// would try to create a bucket with "" as the name, which would get you an error from the GCS functions. gs:/// would cause an array out of bounds exception when i try to get that bucket name after splitting the string. I'll add a check for that last case.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 18 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: The doc says if you can't get an input stream from the resource then it should be false.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 17 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Yea I'll make the change. Originally I had wanted it to return the name only if it exists, but that's not necessary.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 11 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Yea this makes sense. I'll make the change

File: spring-cloud-gcp-storage/src/test/java/org/springframework/cloud/gcp/storage/GoogleStorageTests.java (hunk 19 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/test/java/org/springframework/cloud/gcp/storage/GoogleStorageTests.java]: Changes made, please take a look :)

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 21]
```diff
@@ -73,6 +73,17 @@ public void setResourceLoader(ResourceLoader resourceLoader) {
 	@Override
 	public Resource resolve(String location, ResourceLoader resourceLoader) {
 		if (location.startsWith(PROTOCOL)) {
+
+			String pathWithoutProtocol = location.substring(PROTOCOL.length());
+
+			String[] pathParts = pathWithoutProtocol.split("/");
+
+			if (pathParts.length == 0 || pathWithoutProtocol.isEmpty()) {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Could be nice to throw an exception here saying the path is invalid?
Spring's `Assert` library is nice for that.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 22]
```diff
@@ -84,7 +95,18 @@ public Resource resolve(String location, ResourceLoader resourceLoader) {
...
 			}
-			return new GoogleStorageResource(this.storage, location, this.settings.isAutoCreateFiles());
+
+			Resource resource;
+
+			if (pathParts.length < 2) {
+				resource = new GoogleStorageResourceBucket(this.storage, bucketName,
+						this.settings.isAutoCreateFiles());
+			}
+			else {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: The local variable `resource` is unnecessary.
You can get rid of it and this else by returning where you have `resource =`

Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Yea I had it like that before, but with the return-null for the gs:/// path above it is 4  return statements in the function and checkstyle disallows that.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java [hunk 23]
```diff
@@ -0,0 +1,150 @@
...
+ *
+ * @author Chengyuan Zhao
+ */
+public class GoogleStorageResourceBucket implements WritableResource {
+
+	private final Storage storage;
+
+	private final String bucketName;
+
+	private final boolean createBucketIfRequired;
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: Where do we stand regarding automatic bucket creation?
@meltsufin suggested we shouldn't be doing it, and I'm tempted to agree.
I think users are expected to create the buckets on their own, even more so because bucket names are unique across GCS.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java [hunk 24]
```diff
@@ -180,4 +185,10 @@ public OutputStream getOutputStream() throws IOException {
 		}
 		return Channels.newOutputStream(throwExceptionForNullBlob(blob).writer());
 	}
+
+	@VisibleForTesting
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: This is actually used by `createBlob()`, so it might make sense to remove `@VisibleForTesting`.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 23 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I thought you were on board with the idea at the beginning? Tbh I think intentionally not giving this functionality  would be paternalism/parentalism. The API for creating buckets is super simple to use, and people could go wild with that with minimal effort as it is. Also, since we primarily let people use this functionality via @Value() annotations in source code, that's not conducive to wanton bucket creation anyway.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 22 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: You might be able to remove the previous `return null` if you throw an exception for invalid path, which I think is actually the better way to go there.
If that doesn't help, feel free to ship like this, though that checkstyle rule has annoyed me before too...

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java (hunk 23 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java]: I don't really have strong feelings on this matter.
You do have a point that there is an API for that already and we're just making it easy for users.

So, if @meltsufin is aboard, I'm OK with shipping this feature.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java (hunk 24 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java]: Ah yes, will fix.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 22 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: That sounds like the way to go. Will change.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 21 above)
Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Actually, I think this function should return null for any situation other than success. Looking at the parent's javadoc, it says something like that, and does not throw something like IOException.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java (hunk 22 above)
Comment (joaoandremartins) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: I would also change the first if to `if (!location.startsWith(PROTOCOL)) { return null; }`, so that the whole method doesn't need to be inside the while loop and doesn't end with that `return null`.

File: spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java [hunk 25]
```diff
@@ -72,7 +72,9 @@ public void setResourceLoader(ResourceLoader resourceLoader) {
 
 	@Override
 	public Resource resolve(String location, ResourceLoader resourceLoader) {
-		if (location.startsWith(PROTOCOL)) {
```
Comment (joaoandremartins) [inline spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Indendation doesn't seem right

Comment (ChengyuanZhao) [reply spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageProtocolResolver.java]: Ah yea, I felt like it looked wrong. I just installed intellij again here and I found this formatting file (https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml) is that the right one?
