### PR TITLE
pagination and sort in annotated queries

### LINKED ISSUE #1490: Get Cursor from DatastoreRepository Response
Hello, 

I have a custom `Query` on my Repository method. This is what it looks like
```
public interface PostReplyRepository extends DatastoreRepository<PostReply, Long> {
	@Query("SELECT * FROM postReply WHERE __key__ HAS ANCESTOR @parentPostKey")
	List<PostReply> getRepliesForPostWithId(@Param("parentPostKey") Key parentPostKey);
}
```
It works so far, but i would like to have the Cursor included in the Response. Am I using the wrong return value with a `List` or is it not supported?

### LINKED ISSUE #1570: Support Pagination for @Query annotated methods
I'd like to do a custom query on a repository which i need to search by ancestor releations.
So my method looks like this:
```java
	@Query("SELECT * FROM child WHERE __key__ HAS ANCESTOR @parentKey")
	Page<Post> findAllByParentKeyOrderByNameDesc(@Param("parentKey") Key parentKey, Pageable pageable);
```
([GQL-Docs](https://cloud.google.com/datastore/docs/reference/gql_reference#operators_and_comparisons))

But using this method with a REST endpoint results in a `DatastoreDataException`:
```plain
org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class org.springframework.data.domain.PageRequest to Datastore supported type.
     at org.springframework.cloud.gcp.data.datastore.core.convert.DatastoreNativeTypes.wrapValue(DatastoreNativeTypes.java:166)
     at org.springframework.cloud.gcp.data.datastore.core.convert.TwoStepsConversions.convertOnWriteSingle(TwoStepsConversions.java:320)
     at org.springframework.cloud.gcp.data.datastore.repository.query.GqlDatastoreQuery.bindArgsToGqlQuery(GqlDatastoreQuery.java:233)
     at org.springframework.cloud.gcp.data.datastore.repository.query.GqlDatastoreQuery.execute(GqlDatastoreQuery.java:118)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
     at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
     at com.sun.proxy.$Proxy97.findAllByParentKeyOrderByNameDesc(Unknown Source)
```

Am i doing this wrong?

### PR DESCRIPTION
**Pull request by dmitry-s**
Add support for pagination and sorting to annotation-based queries. Supports Slice and Page return type.

fixes #1490 
fixes #1570

### CODE REVIEW

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 1]
```diff
@@ -267,10 +288,84 @@ boolean isNonEntityReturnedType(Class returnedType) {
 			this.finalGql = spelEvaluator.getQueryString();
 
 			for (Map.Entry<String, Object> entry : results.entrySet()) {
-				this.params.add(entry.getValue());
-				// Cloud Datastore requires the tag name without the
+				Object value = entry.getValue();
+				this.params.add(value);
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Change back to one line

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 2]
```diff
@@ -267,10 +288,84 @@ boolean isNonEntityReturnedType(Class returnedType) {
...
+				// Cloud Datastore requires the tag name without the @
 				this.tagsOrdered.add(entry.getKey().substring(1));
 			}
+
+			ParameterAccessor paramAccessor =
+					new ParametersParameterAccessor(getQueryMethod().getParameters(), rawParams);
+			Sort sort = paramAccessor.getSort();
+			if (!sort.equals(Sort.unsorted())) {
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Move the check to the addSort method

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 3]
```diff
@@ -267,10 +288,84 @@ boolean isNonEntityReturnedType(Class returnedType) {
...
+				this.finalGql = addSort(this.finalGql, sort);
+			}
+			this.noLimitQuery = this.finalGql;
+			Pageable pageable = paramAccessor.getPageable();
+			if (!pageable.equals(Pageable.unpaged())) {
+				this.finalGql += LIMIT_CLAUSE;
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Consider StringBuilder append

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 4]
```diff
@@ -267,10 +288,84 @@ boolean isNonEntityReturnedType(Class returnedType) {
...
+			}
+			return builder.build();
+		}
+
+		private String addSort(String finalGql, Sort sort) {
+			//similar to Spring Data JPA, we don't map passed sort properties to persistent properties names
+			// in @Query annotated methods
+			String orderString = sort.stream().map(order -> order.getProperty() + " " + order.getDirection())
+					.collect(Collectors.joining(", "));
+			return finalGql + " ORDER BY " + orderString;
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Make "ORDER BY" a constant

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 5]
```diff
@@ -120,38 +128,64 @@ public Object execute(Object[] parameters) {
...
-			else {
 
-				result = convertSingularResult(returnedItemType, isNonEntityReturnType,
-						rawResult);
-			}
+			Pageable pageable = DatastorePageable.from(pageableParam, found.getCursor(), count);
+			result = new PageImpl(resultsList, pageable, count);
+		}
+		else if (this.queryMethod.isSliceQuery()) {
+			List resultsList = this.datastoreTemplate.getDatastoreEntityConverter()
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Repeated line from the pageable block

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 6]
```diff
@@ -120,38 +128,64 @@ public Object execute(Object[] parameters) {
...
-			result = convertCollectionResult(returnedItemType, isNonEntityReturnType,
-					rawResult);
-		}
-		else {
-			if (rawResult.isEmpty()) {
-				result = null;
+		Object result = null;
+
+		if (this.queryMethod.isPageQuery()) {
+			List resultsList = this.datastoreTemplate.getDatastoreEntityConverter()
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: Please make this a separate method. `execute` is getting way too long.

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java [hunk 7]
```diff
@@ -120,38 +128,64 @@ public Object execute(Object[] parameters) {
...
+					.getConversions().convertOnRead(rawResult, List.class, returnedItemType);
+			ParameterAccessor paramAccessor = new ParametersParameterAccessor(getQueryMethod().getParameters(),
+					parameters);
+
+			Pageable pageableParam = paramAccessor.getPageable();
+			Long count = pageableParam instanceof DatastorePageable
+					? ((DatastorePageable) pageableParam).getTotalCount()
+					: null;
+			if (count == null) {
+				parsedQueryWithTagsAndValues.switchToNoliminQuery();
```
Comment (meltsufin) [inline spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: s/limin/limit

File: spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java (hunk 3 above)
Comment (dmitry-s) [reply spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/GqlDatastoreQuery.java]: it get's optimized to StringBuilder by compiler anyway

**Comment by dmitry-s** [comment]
@ChengyuanZhao @meltsufin PTAL

File: docs/src/main/asciidoc/datastore.adoc [hunk 8]
```diff
@@ -1011,9 +1011,28 @@ public interface TraderRepository extends DatastoreRepository<Trader, String> {
...
+
+  @Query("SELECT * FROM traders WHERE name = @trader_name")
+  Slice<Trader> tradersByNameSlice(@Param("trader_name") String traderName, Pageable pageable);
+
+  @Query("SELECT * FROM traders WHERE name = @trader_name")
+  Page<Trader> tradersByNamePage(@Param("trader_name") String traderName, Pageable pageable);
 }
 ----
 
+When return type is Slice or Pageable, the cursor that points to position after the result is preserved. In order to leverage it to make queries more efficient, use Pageable produced by `slice.getPageable().next()` (same for Page).
```
Comment (ChengyuanZhao) [inline docs/src/main/asciidoc/datastore.adoc]:
```suggestion
When return type is `Slice` or `Page`, the cursor that points to position after the result is preserved. In order to leverage it to make queries more efficient, use `Pageable` produced by `slice.getPageable().next()` (same for `Page`).
```

Comment (meltsufin) [inline docs/src/main/asciidoc/datastore.adoc]:
```suggestion
When the return type is `Slice` or `Pageable`, the result set cursor that points to the position just after the page is preserved in the returned `Slice` or `Page` object. To take advantage of the cursor to query for the next page or slice, use `result.getPageable().next()`.
```

File: docs/src/main/asciidoc/datastore.adoc [hunk 9]
```diff
@@ -1011,9 +1011,28 @@ public interface TraderRepository extends DatastoreRepository<Trader, String> {
...
+
+NOTE: `Page` requires total count of entities produced by the query, therefore the first query will have to retrieve all the records just to count them. Instead, we recommend using `Slice` return type, because it does not require a count query.
```
Comment (meltsufin) [inline docs/src/main/asciidoc/datastore.adoc]:
```suggestion
NOTE: `Page` requires the total count of entities produced by the query. Therefore, the first query will have to retrieve all of the records just to count them. Instead, we recommend using the `Slice` return type, because it does not require an additional count query.
```
